### ISSUE TITLE
Running a simulation

### ISSUE THREAD

**Issue by bencebako99** [lasseufpa/ITU-Challenge-ML5G-PHY-RL#1]
If trying to perform a simulation (to generate episodes other than those to be provided) we would need to run an UE4/AirSim binary (which is not provided). Is that right? If so, is this project accessible somewhere/somehow?

**Comment by felipebastosb** [comment]
Yes, if one wants to generate new episodes, he /she can use the UE4/AirSim binary (called CaviarRenderer-ITU-v1) that will be provided. But note that the new episodes cannot be used to train the model for this specific 2021 ITU Challenge. The reason for providing the CaviarRenderer-ITU-v1 is that we will continue to promote CAVIAR tools as open-source, for people willing to conduct research using it (and eventually contribute to the codebase).

**Comment by felipebastosb** [comment]
We will provide the UE4/AirSim binary this Friday (23/06/2021) at [this repository](https://nextcloud.lasseufpa.org/s/WYZAMbSbdocs2DL)

**Comment by bencebako99** [comment]
Thank you! Research is exactly the reason I asked.
